name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up JDK 21
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test and build with Gradle
        run: ./gradlew clean test bootJar --no-daemon

      - name: Rename JAR for consistency
        run: |
          # Buscamos el jar principal (ignorando el plain.jar) y lo renombramos a helios-sentinel.jar
          find build/libs/ -type f -name "*.jar" ! -name "*-plain.jar" -exec mv {} build/libs/helios-sentinel.jar \;

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/helios-sentinel.jar"
          target: "/home/ec2-user/helios-sentinel/jar/"
          strip_components: 2

      - name: Restart EC2 Service
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart helios-sentinel
            sudo systemctl status helios-sentinel --no-pager
